//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudMvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int Id { get; set; }
        [Required (ErrorMessage ="Yêu Cầu Điền Đầy Đủ Thông Tin")]

        public string Ten { get; set; }
        [Required(ErrorMessage = "Yêu Cầu Điền Đầy Đủ Thông Tin")]
        public Nullable<int> CMND { get; set; }
        [Required(ErrorMessage = "Yêu Cầu Điền Đầy Đủ Thông Tin")]
        public Nullable<int> Tuoi { get; set; }
        [Required(ErrorMessage = "Yêu Cầu Điền Đầy Đủ Thông Tin")]
        public Nullable<int> Phone { get; set; }
        [Required(ErrorMessage = "Yêu Cầu Điền Đầy Đủ Thông Tin")]
        public string BaoHiem { get; set; }
    }
}
